services:
  clash-host:
    # 若需本地构建镜像，放开 4、5 行注释并注释掉 6 行
    # build: ./build
    # image: clash-host:latest
    image: m.ixdev.cn/ghcr.io/hypooo/clash-host:latest
    container_name: clash-host
    network_mode: host
    restart: unless-stopped
    environment:
      - SUBSCRIBE_URL=订阅链接或远程 yml 配置文件链接
    # 若需使用本地配置文件，放开下面 volumes 配置注释，并将 ./config.yaml 替换为本地配置文件路径，优先级高于 SUBSCRIBE_URL 环境变量
    # volumes:
    #   - ./config.yaml:/etc/mihomo/config.yaml