services:
  clash-host:
    # 本地构建镜像，放开 4、5 行注释并注释掉 6 行
    # build: ./build
    # image: clash-host:latest
    image: m.ixdev.cn/ghcr.io/hypooo/clash-host:latest
    container_name: clash-host
    network_mode: host
    restart: unless-stopped
    environment:
      - SUBSCRIBE_URL=订阅链接或远程 yml 配置文件链接